-- Estrutura preparada para a próxima etapa do piloto.
-- Ainda não execute este arquivo: primeiro criaremos o projeto no Supabase.

create table public.projects (
  id bigint generated by default as identity primary key,
  slug text unique not null,
  department text not null default 'Secretaria de Obras',
  name text not null,
  description text,
  location text,
  responsible text,
  start_date date,
  deadline date,
  unit text not null,
  target numeric not null default 0,
  completed numeric not null default 0,
  budget numeric not null default 0,
  spent numeric not null default 0,
  status text not null default 'nao-iniciado'
    check (status in ('nao-iniciado', 'no-prazo', 'atencao', 'atrasado', 'concluido')),
  next_step text,
  issue text,
  updated_at timestamptz not null default now()
);

create table public.project_updates (
  id bigint generated by default as identity primary key,
  project_id bigint not null references public.projects(id) on delete cascade,
  completed numeric not null,
  spent numeric not null,
  status text not null,
  next_step text,
  issue text,
  created_at timestamptz not null default now()
);

alter table public.projects enable row level security;
alter table public.project_updates enable row level security;

-- A leitura pública será adequada apenas ao piloto com dados fictícios.
create policy "Leitura dos projetos"
on public.projects for select
to anon, authenticated
using (true);

-- Escrita ficará restrita a usuários autenticados.
create policy "Usuários autenticados atualizam projetos"
on public.projects for update
to authenticated
using (true)
with check (true);

create policy "Usuários autenticados cadastram projetos"
on public.projects for insert
to authenticated
with check (true);

create policy "Usuários autenticados excluem projetos"
on public.projects for delete
to authenticated
using (true);

create policy "Usuários autenticados registram histórico"
on public.project_updates for insert
to authenticated
with check (true);

create policy "Usuários autenticados consultam histórico"
on public.project_updates for select
to authenticated
using (true);

grant usage on schema public to anon, authenticated;
grant select on public.projects to anon, authenticated;
grant insert, update, delete on public.projects to authenticated;
grant select, insert on public.project_updates to authenticated;
grant usage, select on all sequences in schema public to authenticated;

insert into public.projects (
  slug, name, description, location, responsible, start_date, deadline,
  unit, target, completed, budget, spent, status, next_step, issue
) values
(
  'recapeamento-vias-urbanas',
  'Recapeamento de vias urbanas',
  'Recapeamento e recuperação do pavimento de ruas do município.',
  'Diversos bairros',
  'Secretaria Municipal de Obras',
  '2026-01-15', '2026-12-20', 'ruas', 80, 48, 4800000, 2900000,
  'no-prazo',
  'Continuar o recapeamento nos bairros programados.',
  'Nenhum impedimento relevante.'
),
(
  'drenagem-urbana',
  'Obras de drenagem urbana',
  'Implantação e melhoria da drenagem para reduzir pontos de alagamento.',
  'Quatro bairros',
  'Secretaria Municipal de Obras',
  '2026-02-10', '2027-03-30', 'bairros', 4, 1, 3200000, 1100000,
  'atencao',
  'Concluir as galerias pluviais do segundo bairro.',
  'Cronograma afetado pelo período de chuvas.'
),
(
  'reforma-praca-central',
  'Reforma da Praça Central',
  'Revitalização do paisagismo, iluminação, calçadas e mobiliário urbano.',
  'Centro',
  'Secretaria Municipal de Obras',
  '2026-03-05', '2026-10-15', 'percentual', 100, 82, 1250000, 980000,
  'no-prazo',
  'Finalizar a iluminação e instalar o mobiliário urbano.',
  'Nenhum impedimento relevante.'
);

alter publication supabase_realtime add table public.projects;
